# Core accent palette (Sonokai)
#ff6578   # red
#f69c5e   # orange
#eacb64   # yellow
#9dd274   # green
#72cce8   # blue
#ba9cf3   # purple
#7ad5f1   # cyan / bright-blue

[mgr]
cwd = { fg = "white" }

hovered         = { reversed = true }
preview_hovered = { reversed = true }

find_keyword  = { bg = "white", fg = "#ff6578", bold = true }

tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

count_copied   = { fg = "#1f1f28", bg = "#9dd274" }  # green
count_cut      = { fg = "#1f1f28", bg = "#ff6578" }  # red
count_selected = { fg = "#1f1f28", bg = "#eacb64" }  # yellow

border_symbol = " "
border_style  = { bg = "#2a2f38", fg = "#373c4b" }   # bg0 / bg2

[mode]
normal_main = { fg = "#333846", bg = "#a5e179", bold = true }
select_main = { fg = "#333846", bg = "#ff6d7e", bold = true }
unset_main  = { fg = "#333846", bg = "#eacb64", bold = true }

normal_alt  = { fg = "#9dd274", bg = "#394634" }
select_alt  = { fg = "#ff6578", bg = "#55393d" }
unset_alt   = { fg = "#eacb64", bg = "#4e432f" }

[status]
overall = { fg = "reset", bg = "#2a2f38" }

sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

perm_type  = { fg = "#f69c5e" }
perm_read  = { fg = "#eacb64" }
perm_write = { fg = "#ff6578" }
perm_exec  = { fg = "#9dd274" }
perm_sep   = { fg = "#828a9a" }

progress_label  = { fg = "#72cce8", bg = "#333846", bold = true }  # blue
progress_normal = { fg = "#333846", bg = "#1f1f28" }
progress_error  = { fg = "#333846", bg = "#1f1f28" }

[which]
cols = 2
mask = { bg = "#181a1c" }             # black
cand = { fg = "white" }
rest = { fg = "#828a9a" }             # grey
desc = { fg = "#5a6477" }             # grey_dim
separator = " | "
separator_style = { fg = "#2a2f38" }  # bg0

[input]
border   = { fg = "#72cce8" }  # blue
title    = {}
value    = {}
selected = { reversed = true }

[cmp]
border   = { fg = "#72cce8" }  # blue
active   = { reversed = true }
inactive = {}

[tasks]
border  = { fg = "#72cce8" }  # blue
title   = {}
hovered = { fg = "#ba9cf3" }  # purple

[help]
on      = { fg = "#72cce8" }                  # blue
run     = { fg = "#ba9cf3" }                  # purple
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "#181a1c", bg = "#e1e3e4" }  # black text on fg-white

[filetype]
rules = [
  { mime = "image/*",             fg = "#eacb64" },  # yellow
  { mime = "{audio,video}/*",     fg = "#9dd274" },  # green
  { mime = "application/{,g}zip", fg = "#ff6578" },  # red
  { mime = "application/x-{tar,bzip*,xz,rar,7z-compressed}", fg = "#ff6578" },
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#72cce8" },
  { name = "*", is = "orphan",    fg = "#ff6578" },
  { name = "*", is = "exec",      fg = "#9dd274" },
  { name = "*/",                  fg = "#7ad5f1" },  # cyan-ish
]
